 # MIT License
 #
 # Copyright (c) 2018 Lotus Engineering, LLC
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
 # in the Software without restriction, including without limitation the rights
 # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 # copies of the Software, and to permit persons to whom the Software is
 # furnished to do so, subject to the following conditions:
 #
 # The above copyright notice and this permission notice shall be included in all
 # copies or substantial portions of the Software.
 #
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.

#
# Autogenerated Python Script from test_evt_par.tcl
#

import sys
import pytest
import struct
from qspypy.qspy import FILTER, QS_OBJ_KIND


def on_reset(qutest):
    qutest.expect_pause()
    qutest.glb_filter(FILTER.UA)
    qutest.current_obj(QS_OBJ_KIND.SM_AO,"AO_MyAO")
    qutest.Continue()


def test_EVT0(qutest):
    qutest.dispatch("MY_EVT0_SIG")
    qutest.expect("%timestamp MY_EVT0")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

def test_EVT1(qutest):
    qutest.dispatch("MY_EVT1_SIG", struct.pack('< I', 12345))
    qutest.expect("%timestamp MY_EVT1 12345")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

def test_EVT2(qutest):
    qutest.dispatch("MY_EVT2_SIG", struct.pack('< I H', 0x1234,678))
    qutest.expect("%timestamp MY_EVT2 4660 678")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

def test_EVT2(qutest):
    qutest.dispatch("MY_EVT3_SIG", struct.pack('< I H B', 87654, 0xdead, 123))
    qutest.expect("%timestamp MY_EVT3 87654 57005 123")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")



if __name__ == "__main__":
    options = ['-x', '-v', '--tb=short']
    options.extend(sys.argv)
    pytest.main(options)
