 # MIT License
 #
 # Copyright (c) 2018 Lotus Engineering, LLC
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
 # in the Software without restriction, including without limitation the rights
 # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 # copies of the Software, and to permit persons to whom the Software is
 # furnished to do so, subject to the following conditions:
 #
 # The above copyright notice and this permission notice shall be included in all
 # copies or substantial portions of the Software.
 #
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.

#
# Autogenerated Python Script from test_probe.tcl
#
import sys
import pytest
import struct
from qspypy.qspy import FILTER, QS_OBJ_KIND


def on_setup(qutest):
    qutest.expect("%timestamp ON_TEST_SETUP")

def on_teardown(qutest):
    qutest.expect("%timestamp ON_TEST_TEARDOWN")



def test_Single_Test_Probe(qutest):
    qutest.command("COMMAND_X")
    qutest.expect("%timestamp COMMAND_X 0")
    qutest.expect("%timestamp Trg-Done QS_RX_COMMAND")
    qutest.probe("myFun",1)
    qutest.command("COMMAND_X")
    qutest.expect("%timestamp TstProbe Fun=myFun,Data=1")
    qutest.expect("%timestamp COMMAND_X 1")
    qutest.expect("%timestamp Trg-Done QS_RX_COMMAND")
    qutest.command("COMMAND_X")
    qutest.expect("%timestamp COMMAND_X 0")
    qutest.expect("%timestamp Trg-Done QS_RX_COMMAND")

def test_Multiple_Test_Probes(qutest_noreset):
    qutest = qutest_noreset # name change
    qutest.probe("myFun",100022)
    qutest.probe("myFun",200033)
    qutest.command("COMMAND_X")
    qutest.expect("%timestamp TstProbe Fun=myFun,Data=100022")
    qutest.expect("%timestamp COMMAND_X 100022")
    qutest.expect("%timestamp Trg-Done QS_RX_COMMAND")
    qutest.command("COMMAND_X")
    qutest.expect("%timestamp TstProbe Fun=myFun,Data=200033")
    qutest.expect("%timestamp COMMAND_X 200033")
    qutest.expect("%timestamp Trg-Done QS_RX_COMMAND")
    qutest.command("COMMAND_X")
    qutest.expect("%timestamp COMMAND_X 0")
    qutest.expect("%timestamp Trg-Done QS_RX_COMMAND")



if __name__ == "__main__":
    options = ['-x', '-v', '--tb=short']
    options.extend(sys.argv)
    pytest.main(options)
